[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.postgres.credentials]
database = "database" # please set me up!
password = "password" # please set me up!
username = "username" # please set me up!
host = "host" # please set me up!
port = 5432
connect_timeout = 15
